---
# handlers file for mysql-user

- name: mysql credentials
  become: yes
  copy:
    content: >
      {
          "initialized": true,
          "name_database": {{ mysql_db_user_database }},
          "mysql_user": {{ mysql_db_user_user }},
          "date": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/mysql-data.fact
