---
# handlers file for mysql-user

- name: Start mysql
  service: name=mysql
           enabled=yes
           state=started
- name: restart mysql
  service: name=mysql
           enabled=yes
           state=restarted
  become: yes
